# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Set Gopath
      run:
        export GOROOT=$HOME/bin/go &&
        export GOBIN=$GOROOT/bin &&
        export GOPATH=$HOME/golang &&
        export PATH=$PATH:$GOBIN

    - name: Build driver
      run:
        cd ./cmd/driver && go build -v -o driver.exe
    - name: Build worker
      run:
        cd ./cmd/worker && go build -v -o worker.exe

    - name: Test
      run: go test -v ./...
